import Video from "../interfaces/video";

export function readRecommendedVideos(): Video[] {
  return [
    {
      id: "001",
      videoLink: "https://www.youtube.com/watch?v=n2RNcPRtAiY",
      thumbnail: "thumbnail-1.webp",
      time: "14:20",
      title: "Talking Tech and AI with Google CEO Sundar Pichai!",
      stats: "3.4M views · 6 months ago",
      channelLink: "https://www.youtube.com/c/mkbhd",
      channelPicture: "channel-1.jpeg",
      channelName: "Marques Brownlee",
      keywords: ["Tech", "AI"],
    },
    {
      id: "002",
      videoLink: "https://www.youtube.com/watch?v=mP0RAo9SKZk",
      thumbnail: "thumbnail-2.webp",
      time: "8:22",
      title: "Try Not To Laugh Challenge #9",
      stats: "19M views · 4 years ago",
      channelLink: "https://www.youtube.com/c/markiplier",
      channelPicture: "channel-2.jpeg",
      channelName: "Markiplier",
      keywords: ["Laugh", "Challenge"],
    },
    {
      id: "003",
      videoLink: "https://www.youtube.com/watch?v=FgjPQQeTh1w",
      thumbnail: "thumbnail-3.webp",
      time: "9:13",
      title: "Crazy Tik Toks Taken Moments Before DISASTER",
      stats: "12M views · 1 year ago",
      channelLink: "https://www.youtube.com/user/SSSniperWolf",
      channelPicture: "channel-3.jpeg",
      channelName: "SSSniperWolf",
      keywords: ["Crazy", "Tik Toks", "DISASTER"],
    },
    {
      id: "004",
      videoLink: "https://www.youtube.com/watch?v=094y1Z2wpJg",
      thumbnail: "thumbnail-4.webp",
      time: "22:09",
      title: "The Simplest Math Problem No One Can Solve - Collatz Conjecture",
      stats: "18M views · 4 months ago",
      channelLink: "https://www.youtube.com/c/veritasium",
      channelPicture: "channel-4.jpeg",
      channelName: "Veritasium",
      keywords: ["Math", "No One", "Conjecture"],
    },
    {
      id: "005",
      videoLink: "https://www.youtube.com/watch?v=86CQq3pKSUw",
      thumbnail: "thumbnail-5.webp",
      time: "11:17",
      title: "Kadane's Algorithm to Maximum Sum Subarray Problem",
      stats: "519K views · 5 years ago",
      channelLink: "https://www.youtube.com/c/CSDojo",
      channelPicture: "channel-5.jpeg",
      channelName: "CS Dojo",
      keywords: ["Kadane", "Algorithm", "Sum"],
    },
    {
      id: "006",
      videoLink: "https://www.youtube.com/watch?v=yXWw0_UfSFg",
      thumbnail: "thumbnail-6.webp",
      time: "19:59",
      title: "Anything You Can Fit In The Circle I’ll Pay For",
      stats: "141M views · 1 year ago",
      channelLink: "https://www.youtube.com/channel/UCX6OQ3DkcsbYNE6H8uQQuVA",
      channelPicture: "channel-6.jpeg",
      channelName: "MrBeast",
      keywords: ["Fit", "Circle", "Pay"],
    },
    {
      id: "007",
      videoLink: "https://www.youtube.com/watch?v=fNVa1qMbF9Y",
      thumbnail: "thumbnail-7.webp",
      time: "10:13",
      title: "Why Planes Don't Fly Over Tibet",
      stats: "6.6M views · 1 year ago",
      channelLink: "https://www.youtube.com/channel/UCP5tjEmvPItGyLhmjdwP7Ww",
      channelPicture: "channel-7.jpeg",
      channelName: "RealLifeLore",
      keywords: ["Planes", "Tibet"],
    },
    {
      id: "008",
      videoLink: "https://www.youtube.com/watch?v=lFm4EM1juls",
      thumbnail: "thumbnail-8.webp",
      time: "7:12",
      title: "Inside The World's Biggest Passenger Plane",
      stats: "3.7M views · 10 months ago",
      channelLink: "https://www.youtube.com/channel/UCHAK6CyegY22Zj2GWrcaIxg",
      channelPicture: "channel-8.jpeg",
      channelName: "Tech Vision",
      keywords: ["Biggest", "Plane"],
    },
    {
      id: "009",
      videoLink: "https://www.youtube.com/watch?v=ixmxOlcrlUc",
      thumbnail: "thumbnail-9.webp",
      time: "13:17",
      title: "The SECRET to Super Human STRENGTH",
      stats: "20M views · 3 year ago",
      channelLink: "https://www.youtube.com/c/OFFICIALTHENXSTUDIOS",
      channelPicture: "channel-9.jpeg",
      channelName: "ThenX",
      keywords: ["SECRET", "Super", "STRENGTH"],
    },
    {
      id: "010",
      videoLink: "https://www.youtube.com/watch?v=R2vXbFp5C9o",
      thumbnail: "thumbnail-10.webp",
      time: "7:53",
      title: "How The World's Largest Cruise Ship Makes 30,000 Meals Every Day",
      stats: "14M views · 1 year ago",
      channelLink: "https://www.youtube.com/user/businessinsider",
      channelPicture: "channel-10.jpeg",
      channelName: "Business Insider",
      keywords: ["Largest", "Cruise", "Meals"],
    },
    {
      id: "011",
      videoLink: "https://www.youtube.com/watch?v=0nZuYyXET3s",
      thumbnail: "thumbnail-11.webp",
      time: "4:10",
      title: "Dubai's Crazy Underwater Train and Other Things #Only in Dubai",
      stats: "3M views · 1 year ago",
      channelLink: "https://www.youtube.com/c/Destinationtips",
      channelPicture: "channel-11.jpeg",
      channelName: "Destination Tips",
      keywords: ["Dubai", "Crazy", "Underwater Train"],
    },
    {
      id: "012",
      videoLink: "https://www.youtube.com/watch?v=9iMGFqMmUFs",
      thumbnail: "thumbnail-12.webp",
      time: "4:51",
      title: "What would happen if you didn’t drink water? - Mia Nacamulli",
      stats: "12M views · 5 years ago",
      channelLink: "https://www.youtube.com/teded",
      channelPicture: "channel-12.jpeg",
      channelName: "TED-Ed",
      keywords: ["happen", "drink", "water"],
    },
  ];
}

export function readVideoHistory(userId: string): Video[] {
  return [];
}
